export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST'
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS'
export const VENDOR_REGISTER_FAIL = 'VENDOR_REGISTER_FAIL'

export const VENDOR_LOGOUT_REQUEST = 'VENDOR_LOGOUT_REQUEST'
export const VENDOR_LOGOUT_SUCCESS = 'VENDOR_LOGOUT_SUCCESS'
export const VENDOR_LOGOUT_FAIL = 'VENDOR_LOGOUT_FAIL'

export const VENDOR_LOGIN_REQUEST = 'VENDOR_LOGIN_REQUEST'
export const VENDOR_LOGIN_SUCCESS = 'VENDOR_LOGIN_SUCCESS'
export const VENDOR_LOGIN_FAIL = 'VENDOR_LOGIN_FAIL'

export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST'
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS'
export const VENDOR_UPDATE_FAIL = 'VENDOR_UPDATE_FAIL'

export const VENDOR_PHOTO_UPLOAD_REQUEST = 'VENDOR_PHOTO_UPLOAD_REQUEST'
export const VENDOR_PHOTO_UPLOAD_SUCCESS = 'VENDOR_PHOTO_UPLOAD_SUCCESS'
export const VENDOR_PHOTO_UPLOAD_FAIL = 'VENDOR_PHOTO_UPLOAD_FAIL'

export const VENDOR_DOCUMENT_UPLOAD_REQUEST = 'VENDOR_DOCUMENT_UPLOAD_REQUEST'
export const VENDOR_DOCUMENT_UPLOAD_SUCCESS = 'VENDOR_DOCUMENT_UPLOAD_SUCCESS'
export const VENDOR_DOCUMENT_UPLOAD_FAIL = 'VENDOR_DOCUMENT_UPLOAD_FAIL'

export const VENDOR_CERTIFICATE_UPLOAD_REQUEST = 'VENDOR_CERTIFICATE_UPLOAD_REQUEST'
export const VENDOR_CERTIFICATE_UPLOAD_SUCCESS = 'VENDOR_CERTIFICATE_UPLOAD_SUCCESS'
export const VENDOR_CERTIFICATE_UPLOAD_FAIL = 'VENDOR_CERTIFICATE_UPLOAD_FAIL'

export const VENDOR_PROFILE_REQUEST = 'VENDOR_PROFILE_REQUEST'
export const VENDOR_PROFILE_SUCCESS = 'VENDOR_PROFILE_SUCCESS'
export const VENDOR_PROFILE_FAIL = 'VENDOR_PROFILE_FAIL'

export const VENDOR_UPDATE_PAYMENT_STATUS_REQUEST = 'VENDOR_UPDATE_PAYMENT_STATUS_REQUEST'
export const VENDOR_UPDATE_PAYMENT_STATUS_SUCCESS = 'VENDOR_UPDATE_PAYMENT_STATUS_SUCCESS'
export const VENDOR_UPDATE_PAYMENT_STATUS_FAIL = 'VENDOR_UPDATE_PAYMENT_STATUS_FAIL'

export const VENDOR_UPDATE_KYC_STATUS_REQUEST = 'VENDOR_UPDATE_KYC_STATUS_REQUEST'
export const VENDOR_UPDATE_KYC_STATUS_SUCCESS = 'VENDOR_UPDATE_KYC_STATUS_SUCCESS'
export const VENDOR_UPDATE_KYC_STATUS_FAIL = 'VENDOR_UPDATE_KYC_STATUS_FAIL'